# Generated by Django 5.2.7 on 2025-11-10 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoredPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام صفحه دسته\u200cبندی')),
                ('page_url', models.URLField(max_length=1000, unique=True, verbose_name='آدرس URL صفحه')),
                ('is_active', models.BooleanField(default=True, verbose_name='آیا فعال است؟')),
                ('last_checked', models.DateTimeField(blank=True, null=True, verbose_name='آخرین زمان بررسی')),
            ],
            options={
                'verbose_name': 'صفحه دسته\u200cبندی تحت نظر',
                'verbose_name_plural': 'صفحات دسته\u200cبندی تحت نظر',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(max_length=1000, unique=True, verbose_name='آدرس صفحه محصول')),
                ('title', models.CharField(blank=True, max_length=300, null=True, verbose_name='عنوان محصول')),
                ('supplier_sku', models.CharField(blank=True, max_length=100, null=True, verbose_name='SKU تامین\u200cکننده')),
                ('brand', models.CharField(blank=True, max_length=100, null=True, verbose_name='مارک')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات محصول')),
                ('supplier_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='قیمت اصلی')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='قیمت با تخفیف')),
                ('is_in_stock', models.BooleanField(default=True, verbose_name='آیا موجود است؟')),
                ('specifications', models.JSONField(blank=True, null=True, verbose_name='مشخصات فنی (JSON)')),
                ('last_scraped_at', models.DateTimeField(blank=True, null=True, verbose_name='آخرین زمان اسکرپ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد رکورد')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام تامین\u200cکننده')),
                ('website_url', models.URLField(blank=True, null=True, verbose_name='آدرس سایت')),
                ('product_link_selector', models.CharField(blank=True, max_length=500, null=True, verbose_name='سلکتور لینک محصول (در صفحه دسته\u200cبندی)')),
                ('next_page_selector', models.CharField(blank=True, max_length=500, null=True, verbose_name='سلکتور صفحه بعد (Pagination)')),
                ('title_selector', models.CharField(blank=True, max_length=500, null=True, verbose_name='سلکتور نام محصول')),
                ('sku_selector', models.CharField(blank=True, max_length=500, null=True, verbose_name='سلکتور کد (SKU)')),
                ('brand_selector', models.CharField(blank=True, max_length=500, null=True, verbose_name='سلکتور مارک (Brand)')),
                ('description_selector', models.CharField(blank=True, max_length=500, null=True, verbose_name='سلکتور توضیحات (Description)')),
                ('price_selector', models.CharField(blank=True, max_length=500, null=True, verbose_name='سلکتور قیمت اصلی')),
                ('sale_price_selector', models.CharField(blank=True, max_length=500, null=True, verbose_name='سلکتور قیمت با تخفیف (Sale Price)')),
                ('in_stock_selector', models.CharField(blank=True, max_length=500, null=True, verbose_name='سلکتور وضعیت موجودی (In Stock)')),
                ('image_selector', models.CharField(blank=True, max_length=500, null=True, verbose_name='سلکتور عکس\u200cهای گالری (Images)')),
                ('specs_selector', models.CharField(blank=True, max_length=500, null=True, verbose_name='سلکتور کانتینر مشخصات فنی (Specs)')),
            ],
            options={
                'verbose_name': 'تامین\u200cکننده',
                'verbose_name_plural': 'تامین\u200cکنندگان',
            },
        ),
        migrations.CreateModel(
            name='ScrapingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SUCCESS', 'موفق (آپدیت شد)'), ('FAILED', 'ناموفق (خطا)'), ('INFO', 'اطلاعات (کشف شد)')], max_length=10, verbose_name='وضعیت')),
                ('message', models.TextField(verbose_name='پیام گزارش')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('monitored_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scraper.monitoredpage')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='scraper.product')),
            ],
            options={
                'verbose_name': 'گزارش ربات',
                'verbose_name_plural': 'گزارش\u200cهای ربات',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='scraper.supplier', verbose_name='تامین\u200cکننده'),
        ),
        migrations.AddField(
            model_name='monitoredpage',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitored_pages', to='scraper.supplier'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=1000, verbose_name='آدرس URL عکس')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='scraper.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'تصویر محصول',
                'verbose_name_plural': 'تصاویر محصول',
                'unique_together': {('product', 'image_url')},
            },
        ),
    ]
