# Generated by Django 5.2.7 on 2025-12-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specifications_translate',
            field=models.JSONField(blank=True, null=True, verbose_name='مشخصات فنی بعد از ترجمه (JSON)'),
        ),
    ]
