# Generated by Django 5.2.7 on 2025-12-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_product_specifications_translate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='needtotranslate',
            field=models.BooleanField(default=False, verbose_name='آیا نیاز به ترنسلیت دارد؟'),
        ),
    ]
