# Generated by Django 5.2.7 on 2025-12-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_product_needtotranslate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_translate',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات محصول بعد ترجمه'),
        ),
    ]
