# Generated by Django 5.2.7 on 2025-12-08 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_product_description_translate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='title_translate',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='عنوان فارسی محصول'),
        ),
    ]
