# Generated by Django 5.2.7 on 2025-12-08 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_product_title_translate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات کوتاه (HTML)'),
        ),
    ]
