# Generated by Django 5.2.7 on 2025-12-08 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0006_product_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_long_desc_generated',
            field=models.BooleanField(default=False, verbose_name='آیا توضیحات بلند ساخته شده؟'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_short_desc_generated',
            field=models.BooleanField(default=False, verbose_name='آیا توضیحات کوتاه ساخته شده؟'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_title_fixed',
            field=models.BooleanField(default=False, verbose_name='آیا عنوان اصلاح شده؟'),
        ),
    ]
